### ISSUE TITLE
Windows install

### ISSUE THREAD

**Issue by cgravill** [antha-lang/antha#1]
Thanks for providing the Windows install.bat, it worked well for me with a few adjustments.

If it would be useful, I can make a pull request with these changes:

Copy glpk_4_55.dll to %GOPATH%\bin (which is in userprofile)
Also add %USERPROFILE%\go\bin to the path, so that e.g. unpathed "antharun" works directly

With that the manual driver works for me on Win8.1 and Win10.

**Comment by ddn0** [comment]
Thanks for pointing out the bug!

The following patch should fix the issue: c3a581fd05c25fc74f766a7cebb522f4f61c9437

I decided to put the glpk_4_55.dll in the C:\MinGW directory to play more nicely with that toolchain. Let me know if you have any more issues. I'll merge in the branch to master shortly.

**Comment by cgravill** [comment]
Great, that's much smoother for the install.

I moved on to "Making and Running Antha Components". The makefile seems to be expecting a UNIX "find" command.

I believe what's happening is that the built-in find.exe in system32 is generally going to be found before the one you presumably want in the #git#/bin? I was able to overcome this by explicitly giving a path to there.

However, I then get

	C:\Users\colin\go\src\github.com\antha-lang\antha>mingw32-make.exe go_from_antha
	cd "antha/component/lib" && \
	        "C:\Program Files (x86)\Git\bin\find" "/c/Users/colin/go/src/github.com/antha-lang/antha/antha/component/an" -name '*.an' -print0 | \
	        "C:\Program Files (x86)\Git\bin\xargs" -0 go run "C:/users/colin/go/src/github.com/antha-lang/antha/cmd/antha/antha.go" -componentLib=true -componentLibPackage="lib" && \
	        gofmt -w -s .
	open <standard input>.go: The filename, directory name, or volume label syntax is incorrect.
	exit status 2
	makefile:16: recipe for target 'go_from_antha' failed
	mingw32-make.exe: *** [go_from_antha] Error 123

Any suggestions?

**Comment by ddn0** [comment]
I decided to just reimplement the required functionality in go.

ad13a10f82..0647b3b should fix your issue.

**Comment by cgravill** [comment]
That works for me, thanks!
