### ISSUE TITLE
SetUpInplate error

### ISSUE THREAD

**Issue by gogogadgetbioprocess** [antha-lang/antha#173]
https://github.com/antha-lang/antha/commit/af265ca0b2e91f916f870892f7afa422b26d0887

Error in adding a plate into the system and then mixing components into that existing plate

```bash
cd $GOPATH/src/github.com/antha-lang/antha
git checkout af265ca0b2e91f916f870892f7afa422b26d0887
cd antha/examples/workflows/ParsePlate
antharun --driver go://github.com/Synthace/PipetMaxDriver/server
```

### Error message:
```
error planning: 8 (LH_ERR_DIRE) : an internal error : Plate disappeared from position position_8
```

**Comment by m-i-sadowski** [comment]
please check out branch fix-parseplate to verify that you are getting the required results

**Comment by gogogadgetbioprocess** [comment]
Yep, that works
