### ISSUE TITLE
MIX_VOL or MIX_VOLUME

### ISSUE THREAD

**Issue by gogogadgetbioprocess** [antha-lang/antha#239]
Unclear as to whether to use PRE_MIX_VOL or PRE_MIX_VOLUME?

ditto POST_MIX

The antharun list policyCommands indicates VOL. However, using that in a policy seems to generate an error (cannot set PRE_MIX_VOL this low).

**Comment by m-i-sadowski** [comment]
Typo in policyCommands... fixed now. Apologies

**Comment by gogogadgetbioprocess** [comment]
Is it in a PR somewhere? It still looks the same on master?

**Comment by m-i-sadowski** [comment]
no, I pushed it straight in
