### ISSUE TITLE
Unwanted re-ordering of parameters 

### ISSUE THREAD

**Issue by chr1sgrant** [antha-lang/antha#301]
Upon running make, the order of inputs in the JSON and YML parameters files are changed to alphabetical order. 

This is also true for the ordering of parameters, inputs, outputs and data in the generated go file for each compiled element.

This is not desirable. Often parameters are grouped together by category or importance and removing this will make wiring up workflows in the editor easier

**Comment by ddn0** [comment]
Order of the fields is not a standard property of yaml or json fields so the cost of implementing this is high. Could be cheaper on a case by case basis if you were more specific about which cases you cared about.

**Comment by chr1sgrant** [comment]
Ok, the order of the json / yml is less important than the order of variables in the go files, can something be done about preserving the order of that?

And also the distinctions between physical and data inputs/outputs? 

This came out as a major usability issue for the workflow editor
