### ISSUE TITLE
inputPlates as config in parameters

### ISSUE THREAD

**Issue by gogogadgetbioprocess** [antha-lang/antha#85]
Using inputPlates doesn't seem to be supported currently, or if so results in an error:

antha-lang/antha#5ebbd7f9 (branch autopcr)

https://github.com/antha-lang/antha/blob/5ebbd7f90ed0ef12ee107999ba5a3664e4e69a43/antha/examples/workflows/Aisha/step3_gradientPCR/parametersPlateConfigerror.yml

antharun --parameters parametersPlateConfigerror.yml --driver localhost:50051

Error: Output plate of type pcrplate_skirted_riser in position position_9
Error: runtime error: invalid memory address or nil pointer dereference

**Comment by ddn0** [comment]
Passing filenames in the config parameters is not supported. You need something like ```antharun --inputPlates``` instead.

See #87 for a better solution.
